services:
  gateway:
    image: gateway
    ports:
      - "5036:8080"
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    depends_on:
      - rabbitmq
        
  email:
    image: email
    build:
      context: .
      dockerfile: EmailDaemon/Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: masstransit/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=ntf
      - RABBITMQ_DEFAULT_PASS=ntf
    ports:
      - "15672:15672"
      - "5672:5672"
        
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.17.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
        
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: user-actions-simulator-backend
    volumes:
      - ./local/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro