<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Gateway</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Elastic.Serilog.Sinks" Version="8.12.3" />
        <PackageReference Include="Kontur.Results" Version="3.0.0" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.4" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8"/>
        <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.10.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.10.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.10.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="1.10.0-beta.1" />
        <PackageReference Include="Serilog" Version="4.2.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Gateway.Models\Gateway.Models.csproj" />
    </ItemGroup>

</Project>
